--
-- PostgreSQL database dump
--

\restrict hw6whXUqyOaQQp9POnHmPjXOaoGLFuMbW38hL6RPzhDzj08f4ZBV5KCdhCr3MUi

-- Dumped from database version 16.12 (Debian 16.12-1.pgdg13+1)
-- Dumped by pg_dump version 16.12 (Debian 16.12-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_jeu; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.admin_jeu (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.admin_jeu OWNER TO escape;

--
-- Name: admin_jeu_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.admin_jeu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_jeu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: code_jeu; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.code_jeu (
    id integer NOT NULL,
    fragment character varying(12) NOT NULL,
    ordre integer NOT NULL
);


ALTER TABLE public.code_jeu OWNER TO escape;

--
-- Name: code_jeu_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.code_jeu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.code_jeu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cont_quiz; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.cont_quiz (
    id integer NOT NULL,
    question text NOT NULL,
    bonne_reponse character varying(255) NOT NULL,
    mauvaises_reponses json NOT NULL,
    mini_jeu_id integer NOT NULL
);


ALTER TABLE public.cont_quiz OWNER TO escape;

--
-- Name: cont_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.cont_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cont_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cont_seq; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.cont_seq (
    id integer NOT NULL,
    libelle character varying(100) NOT NULL,
    ordre_attendu integer NOT NULL,
    zone_app character varying(50) NOT NULL,
    mini_jeu_id integer NOT NULL
);


ALTER TABLE public.cont_seq OWNER TO escape;

--
-- Name: cont_seq_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.cont_seq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cont_seq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cont_tri; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.cont_tri (
    id integer NOT NULL,
    nom_produit character varying(100) NOT NULL,
    est_cosmetique boolean NOT NULL,
    mini_jeu_id integer NOT NULL
);


ALTER TABLE public.cont_tri OWNER TO escape;

--
-- Name: cont_tri_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.cont_tri ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cont_tri_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO escape;

--
-- Name: inventaire_code; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.inventaire_code (
    id integer NOT NULL,
    est_valide boolean NOT NULL,
    session_joueur_id integer NOT NULL,
    code_id integer NOT NULL
);


ALTER TABLE public.inventaire_code OWNER TO escape;

--
-- Name: inventaire_code_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.inventaire_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventaire_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: joueur; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.joueur (
    id integer NOT NULL,
    pseudo character varying(100) NOT NULL
);


ALTER TABLE public.joueur OWNER TO escape;

--
-- Name: joueur_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.joueur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.joueur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mini_jeu; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.mini_jeu (
    id integer NOT NULL,
    nom character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    ordre integer NOT NULL,
    duree_max integer NOT NULL,
    actif boolean NOT NULL
);


ALTER TABLE public.mini_jeu OWNER TO escape;

--
-- Name: mini_jeu_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.mini_jeu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mini_jeu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_jeu; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.session_jeu (
    id integer NOT NULL,
    code_pin character varying(10) NOT NULL,
    est_active boolean NOT NULL,
    date_creation timestamp(0) without time zone NOT NULL,
    code_secret character varying(12) DEFAULT NULL::character varying,
    date_debut timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    date_fin timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    admin_id integer NOT NULL
);


ALTER TABLE public.session_jeu OWNER TO escape;

--
-- Name: session_jeu_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.session_jeu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_jeu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_joueur; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.session_joueur (
    id integer NOT NULL,
    score integer NOT NULL,
    tentatives_code_final integer NOT NULL,
    est_game_over boolean NOT NULL,
    a_gagne boolean NOT NULL,
    date_connexion timestamp(0) without time zone NOT NULL,
    session_id integer NOT NULL,
    joueur_id integer NOT NULL
);


ALTER TABLE public.session_joueur OWNER TO escape;

--
-- Name: session_joueur_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.session_joueur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_joueur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suivi_prog; Type: TABLE; Schema: public; Owner: escape
--

CREATE TABLE public.suivi_prog (
    id integer NOT NULL,
    termine boolean NOT NULL,
    score integer NOT NULL,
    temps integer NOT NULL,
    nb_cosmetique_att integer NOT NULL,
    nb_non_cosmetique_att integer NOT NULL,
    a_gagne_code boolean NOT NULL,
    session_joueur_id integer NOT NULL,
    mini_jeu_id integer NOT NULL
);


ALTER TABLE public.suivi_prog OWNER TO escape;

--
-- Name: suivi_prog_id_seq; Type: SEQUENCE; Schema: public; Owner: escape
--

ALTER TABLE public.suivi_prog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suivi_prog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admin_jeu; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.admin_jeu (id, email, password) FROM stdin;
1	manal@gmail.com	admin
2	admin@gmail.com	admin
3	massylias@gmail.com	admin
4	ryma@gmail.com	admin
\.


--
-- Data for Name: code_jeu; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.code_jeu (id, fragment, ordre) FROM stdin;
1	RGDK	1
2	4537	2
3	THCL	3
\.


--
-- Data for Name: cont_quiz; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.cont_quiz (id, question, bonne_reponse, mauvaises_reponses, mini_jeu_id) FROM stdin;
1	Où jeter un flacon en verre de labo non rincé ?	Conteneur déchets spécifiques	["Poubelle ménagère","Bac de tri verre classique","Évier du laboratoire"]	3
2	Quel est l'impact majeur mesuré par l'ACV ?	Effet de serre	["Consommation d'eau","Bruit industriel","Nombre de ventes"]	3
3	Quelle est la première étape du cycle de vie d'un produit cosmétique ?	Matières Premières	["Packaging","Distribution","Utilisation client"]	3
4	Que signifie l'acronyme ACV dans une démarche d'éco-conception ?	Analyse du Cycle de Vie	["Action Chimique Valide","Apport de Carbone Vert","Achat de Cosmétique Végan"]	3
5	Dans quelle poubelle doit-on jeter l'emballage en carton propre d'une matière première ?	Bac de tri Papier/Carton	["Poubelle de chimie","Conteneur à verre","Incinérateur de sécurité"]	3
\.


--
-- Data for Name: cont_seq; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.cont_seq (id, libelle, ordre_attendu, zone_app, mini_jeu_id) FROM stdin;
1	Nettoyage de la peau	1	Visage	2
2	Gommage exfoliant	2	Visage	2
3	Sérum anti-cernes	3	Yeux	2
4	Crème hydratante	4	Visage	2
5	Baume protecteur	5	Lèvres	2
\.


--
-- Data for Name: cont_tri; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.cont_tri (id, nom_produit, est_cosmetique, mini_jeu_id) FROM stdin;
1	Dentifrice	t	1
2	Complément alimentaire	f	1
3	Shampoing purifiant	t	1
4	Rouge à lèvres mat	t	1
5	Eau de toilette	t	1
6	Crème solaire SPF 50	t	1
7	Masque hydratant	t	1
8	Solution lavage oculaire	f	1
9	Gélules de bronzage	f	1
10	Spray nasal salin	f	1
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260429114214	2026-04-29 12:53:39	395
DoctrineMigrations\\Version20260429120435	2026-04-29 12:53:40	128
\.


--
-- Data for Name: inventaire_code; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.inventaire_code (id, est_valide, session_joueur_id, code_id) FROM stdin;
1	f	1	1
2	f	1	2
3	f	1	3
\.


--
-- Data for Name: joueur; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.joueur (id, pseudo) FROM stdin;
1	les tigres
\.


--
-- Data for Name: mini_jeu; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.mini_jeu (id, nom, type, ordre, duree_max, actif) FROM stdin;
1	Le Tri Express	tri	1	900	t
2	Mission Peau Parfaite	sequence	2	900	t
3	L'Énigme Écologique	quiz	3	900	t
\.


--
-- Data for Name: session_jeu; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.session_jeu (id, code_pin, est_active, date_creation, code_secret, date_debut, date_fin, admin_id) FROM stdin;
1	949113	t	2026-04-29 13:02:39	RGDK4537THCL	2026-04-29 13:02:39	2026-04-29 13:47:39	1
\.


--
-- Data for Name: session_joueur; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.session_joueur (id, score, tentatives_code_final, est_game_over, a_gagne, date_connexion, session_id, joueur_id) FROM stdin;
1	0	0	f	f	2026-04-29 13:02:59	1	1
\.


--
-- Data for Name: suivi_prog; Type: TABLE DATA; Schema: public; Owner: escape
--

COPY public.suivi_prog (id, termine, score, temps, nb_cosmetique_att, nb_non_cosmetique_att, a_gagne_code, session_joueur_id, mini_jeu_id) FROM stdin;
1	f	0	0	0	0	f	1	1
2	f	0	0	0	0	f	1	2
3	f	0	0	0	0	f	1	3
\.


--
-- Name: admin_jeu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.admin_jeu_id_seq', 4, true);


--
-- Name: code_jeu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.code_jeu_id_seq', 3, true);


--
-- Name: cont_quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.cont_quiz_id_seq', 5, true);


--
-- Name: cont_seq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.cont_seq_id_seq', 5, true);


--
-- Name: cont_tri_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.cont_tri_id_seq', 10, true);


--
-- Name: inventaire_code_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.inventaire_code_id_seq', 3, true);


--
-- Name: joueur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.joueur_id_seq', 1, true);


--
-- Name: mini_jeu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.mini_jeu_id_seq', 3, true);


--
-- Name: session_jeu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.session_jeu_id_seq', 1, true);


--
-- Name: session_joueur_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.session_joueur_id_seq', 1, true);


--
-- Name: suivi_prog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: escape
--

SELECT pg_catalog.setval('public.suivi_prog_id_seq', 3, true);


--
-- Name: admin_jeu admin_jeu_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.admin_jeu
    ADD CONSTRAINT admin_jeu_pkey PRIMARY KEY (id);


--
-- Name: code_jeu code_jeu_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.code_jeu
    ADD CONSTRAINT code_jeu_pkey PRIMARY KEY (id);


--
-- Name: cont_quiz cont_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_quiz
    ADD CONSTRAINT cont_quiz_pkey PRIMARY KEY (id);


--
-- Name: cont_seq cont_seq_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_seq
    ADD CONSTRAINT cont_seq_pkey PRIMARY KEY (id);


--
-- Name: cont_tri cont_tri_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_tri
    ADD CONSTRAINT cont_tri_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: inventaire_code inventaire_code_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.inventaire_code
    ADD CONSTRAINT inventaire_code_pkey PRIMARY KEY (id);


--
-- Name: joueur joueur_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.joueur
    ADD CONSTRAINT joueur_pkey PRIMARY KEY (id);


--
-- Name: mini_jeu mini_jeu_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.mini_jeu
    ADD CONSTRAINT mini_jeu_pkey PRIMARY KEY (id);


--
-- Name: session_jeu session_jeu_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.session_jeu
    ADD CONSTRAINT session_jeu_pkey PRIMARY KEY (id);


--
-- Name: session_joueur session_joueur_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.session_joueur
    ADD CONSTRAINT session_joueur_pkey PRIMARY KEY (id);


--
-- Name: suivi_prog suivi_prog_pkey; Type: CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.suivi_prog
    ADD CONSTRAINT suivi_prog_pkey PRIMARY KEY (id);


--
-- Name: idx_82457bad6ef1a51c; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_82457bad6ef1a51c ON public.cont_seq USING btree (mini_jeu_id);


--
-- Name: idx_91e571e86ef1a51c; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_91e571e86ef1a51c ON public.cont_tri USING btree (mini_jeu_id);


--
-- Name: idx_921aa39c613fecdf; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_921aa39c613fecdf ON public.session_joueur USING btree (session_id);


--
-- Name: idx_921aa39ca9e2d76c; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_921aa39ca9e2d76c ON public.session_joueur USING btree (joueur_id);


--
-- Name: idx_9c9d174f6ef1a51c; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_9c9d174f6ef1a51c ON public.suivi_prog USING btree (mini_jeu_id);


--
-- Name: idx_9c9d174fea009266; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_9c9d174fea009266 ON public.suivi_prog USING btree (session_joueur_id);


--
-- Name: idx_b8596d5d27dafe17; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_b8596d5d27dafe17 ON public.inventaire_code USING btree (code_id);


--
-- Name: idx_b8596d5dea009266; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_b8596d5dea009266 ON public.inventaire_code USING btree (session_joueur_id);


--
-- Name: idx_fe031e236ef1a51c; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_fe031e236ef1a51c ON public.cont_quiz USING btree (mini_jeu_id);


--
-- Name: idx_ff3d158f642b8210; Type: INDEX; Schema: public; Owner: escape
--

CREATE INDEX idx_ff3d158f642b8210 ON public.session_jeu USING btree (admin_id);


--
-- Name: uniq_f4e3dec0e7927c74; Type: INDEX; Schema: public; Owner: escape
--

CREATE UNIQUE INDEX uniq_f4e3dec0e7927c74 ON public.admin_jeu USING btree (email);


--
-- Name: uniq_session_joueur_minijeu; Type: INDEX; Schema: public; Owner: escape
--

CREATE UNIQUE INDEX uniq_session_joueur_minijeu ON public.suivi_prog USING btree (session_joueur_id, mini_jeu_id);


--
-- Name: cont_seq fk_82457bad6ef1a51c; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_seq
    ADD CONSTRAINT fk_82457bad6ef1a51c FOREIGN KEY (mini_jeu_id) REFERENCES public.mini_jeu(id);


--
-- Name: cont_tri fk_91e571e86ef1a51c; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_tri
    ADD CONSTRAINT fk_91e571e86ef1a51c FOREIGN KEY (mini_jeu_id) REFERENCES public.mini_jeu(id);


--
-- Name: session_joueur fk_921aa39c613fecdf; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.session_joueur
    ADD CONSTRAINT fk_921aa39c613fecdf FOREIGN KEY (session_id) REFERENCES public.session_jeu(id);


--
-- Name: session_joueur fk_921aa39ca9e2d76c; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.session_joueur
    ADD CONSTRAINT fk_921aa39ca9e2d76c FOREIGN KEY (joueur_id) REFERENCES public.joueur(id);


--
-- Name: suivi_prog fk_9c9d174f6ef1a51c; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.suivi_prog
    ADD CONSTRAINT fk_9c9d174f6ef1a51c FOREIGN KEY (mini_jeu_id) REFERENCES public.mini_jeu(id);


--
-- Name: suivi_prog fk_9c9d174fea009266; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.suivi_prog
    ADD CONSTRAINT fk_9c9d174fea009266 FOREIGN KEY (session_joueur_id) REFERENCES public.session_joueur(id);


--
-- Name: inventaire_code fk_b8596d5d27dafe17; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.inventaire_code
    ADD CONSTRAINT fk_b8596d5d27dafe17 FOREIGN KEY (code_id) REFERENCES public.code_jeu(id);


--
-- Name: inventaire_code fk_b8596d5dea009266; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.inventaire_code
    ADD CONSTRAINT fk_b8596d5dea009266 FOREIGN KEY (session_joueur_id) REFERENCES public.session_joueur(id);


--
-- Name: cont_quiz fk_fe031e236ef1a51c; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.cont_quiz
    ADD CONSTRAINT fk_fe031e236ef1a51c FOREIGN KEY (mini_jeu_id) REFERENCES public.mini_jeu(id);


--
-- Name: session_jeu fk_ff3d158f642b8210; Type: FK CONSTRAINT; Schema: public; Owner: escape
--

ALTER TABLE ONLY public.session_jeu
    ADD CONSTRAINT fk_ff3d158f642b8210 FOREIGN KEY (admin_id) REFERENCES public.admin_jeu(id);


--
-- PostgreSQL database dump complete
--

\unrestrict hw6whXUqyOaQQp9POnHmPjXOaoGLFuMbW38hL6RPzhDzj08f4ZBV5KCdhCr3MUi

