<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331161313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE code_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fragment VARCHAR(12) NOT NULL, ordre INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE inventaire_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, est_valide BOOLEAN NOT NULL, session_id INT NOT NULL, code_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8596D5D613FECDF ON inventaire_code (session_id)');
        $this->addSql('CREATE INDEX IDX_B8596D5D27DAFE17 ON inventaire_code (code_id)');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT FK_B8596D5D613FECDF FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT FK_B8596D5D27DAFE17 FOREIGN KEY (code_id) REFERENCES code_jeu (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT FK_B8596D5D613FECDF');
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT FK_B8596D5D27DAFE17');
        $this->addSql('DROP TABLE code_jeu');
        $this->addSql('DROP TABLE inventaire_code');
    }
}
