<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429114214 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4E3DEC0E7927C74 ON admin_jeu (email)');
        $this->addSql('CREATE TABLE code_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fragment VARCHAR(12) NOT NULL, ordre INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cont_quiz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, bonne_reponse VARCHAR(255) NOT NULL, mauvaises_reponses JSON NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE031E236EF1A51C ON cont_quiz (mini_jeu_id)');
        $this->addSql('CREATE TABLE cont_seq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(100) NOT NULL, ordre_attendu INT NOT NULL, zone_app VARCHAR(50) NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_82457BAD6EF1A51C ON cont_seq (mini_jeu_id)');
        $this->addSql('CREATE TABLE cont_tri (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_produit VARCHAR(100) NOT NULL, est_cosmetique BOOLEAN NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91E571E86EF1A51C ON cont_tri (mini_jeu_id)');
        $this->addSql('CREATE TABLE inventaire_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, est_valide BOOLEAN NOT NULL, session_id INT NOT NULL, code_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8596D5D613FECDF ON inventaire_code (session_id)');
        $this->addSql('CREATE INDEX IDX_B8596D5D27DAFE17 ON inventaire_code (code_id)');
        $this->addSql('CREATE TABLE joueur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE mini_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, ordre INT NOT NULL, duree_max INT NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE session_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_pin VARCHAR(10) NOT NULL, est_active BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, score INT NOT NULL, code_secret VARCHAR(12) DEFAULT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, admin_id INT NOT NULL, joueur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF3D158F642B8210 ON session_jeu (admin_id)');
        $this->addSql('CREATE INDEX IDX_FF3D158FA9E2D76C ON session_jeu (joueur_id)');
        $this->addSql('CREATE TABLE suivi_prog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, termine BOOLEAN NOT NULL, score INT NOT NULL, temps INT NOT NULL, nb_cosmetique_att INT NOT NULL, nb_non_cosmetique_att INT NOT NULL, a_gagne_code BOOLEAN NOT NULL, session_id INT NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C9D174F613FECDF ON suivi_prog (session_id)');
        $this->addSql('CREATE INDEX IDX_9C9D174F6EF1A51C ON suivi_prog (mini_jeu_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_minijeu ON suivi_prog (session_id, mini_jeu_id)');
        $this->addSql('ALTER TABLE cont_quiz ADD CONSTRAINT FK_FE031E236EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cont_seq ADD CONSTRAINT FK_82457BAD6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cont_tri ADD CONSTRAINT FK_91E571E86EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT FK_B8596D5D613FECDF FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT FK_B8596D5D27DAFE17 FOREIGN KEY (code_id) REFERENCES code_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_jeu ADD CONSTRAINT FK_FF3D158F642B8210 FOREIGN KEY (admin_id) REFERENCES admin_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_jeu ADD CONSTRAINT FK_FF3D158FA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT FK_9C9D174F613FECDF FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT FK_9C9D174F6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cont_quiz DROP CONSTRAINT FK_FE031E236EF1A51C');
        $this->addSql('ALTER TABLE cont_seq DROP CONSTRAINT FK_82457BAD6EF1A51C');
        $this->addSql('ALTER TABLE cont_tri DROP CONSTRAINT FK_91E571E86EF1A51C');
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT FK_B8596D5D613FECDF');
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT FK_B8596D5D27DAFE17');
        $this->addSql('ALTER TABLE session_jeu DROP CONSTRAINT FK_FF3D158F642B8210');
        $this->addSql('ALTER TABLE session_jeu DROP CONSTRAINT FK_FF3D158FA9E2D76C');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT FK_9C9D174F613FECDF');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT FK_9C9D174F6EF1A51C');
        $this->addSql('DROP TABLE admin_jeu');
        $this->addSql('DROP TABLE code_jeu');
        $this->addSql('DROP TABLE cont_quiz');
        $this->addSql('DROP TABLE cont_seq');
        $this->addSql('DROP TABLE cont_tri');
        $this->addSql('DROP TABLE inventaire_code');
        $this->addSql('DROP TABLE joueur');
        $this->addSql('DROP TABLE mini_jeu');
        $this->addSql('DROP TABLE session_jeu');
        $this->addSql('DROP TABLE suivi_prog');
    }
}
