<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260228201529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cont_quiz (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question TEXT NOT NULL, bonne_reponse VARCHAR(255) NOT NULL, mauvaises_reponses JSON NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE031E236EF1A51C ON cont_quiz (mini_jeu_id)');
        $this->addSql('CREATE TABLE cont_seq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(100) NOT NULL, ordre_attendu INT NOT NULL, zone_app VARCHAR(50) NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_82457BAD6EF1A51C ON cont_seq (mini_jeu_id)');
        $this->addSql('CREATE TABLE cont_tri (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_produit VARCHAR(100) NOT NULL, est_cosmetique BOOLEAN NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_91E571E86EF1A51C ON cont_tri (mini_jeu_id)');
        $this->addSql('CREATE TABLE mini_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, ordre INT NOT NULL, duree_max INT NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE suivi_prog (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, termine BOOLEAN NOT NULL, score INT NOT NULL, temps INT NOT NULL, nb_cosmetique_att INT NOT NULL, nb_non_cosmetique_att INT NOT NULL, session_id INT NOT NULL, mini_jeu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9C9D174F613FECDF ON suivi_prog (session_id)');
        $this->addSql('CREATE INDEX IDX_9C9D174F6EF1A51C ON suivi_prog (mini_jeu_id)');
        $this->addSql('ALTER TABLE cont_quiz ADD CONSTRAINT FK_FE031E236EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cont_seq ADD CONSTRAINT FK_82457BAD6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cont_tri ADD CONSTRAINT FK_91E571E86EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT FK_9C9D174F613FECDF FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT FK_9C9D174F6EF1A51C FOREIGN KEY (mini_jeu_id) REFERENCES mini_jeu (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cont_quiz DROP CONSTRAINT FK_FE031E236EF1A51C');
        $this->addSql('ALTER TABLE cont_seq DROP CONSTRAINT FK_82457BAD6EF1A51C');
        $this->addSql('ALTER TABLE cont_tri DROP CONSTRAINT FK_91E571E86EF1A51C');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT FK_9C9D174F613FECDF');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT FK_9C9D174F6EF1A51C');
        $this->addSql('DROP TABLE cont_quiz');
        $this->addSql('DROP TABLE cont_seq');
        $this->addSql('DROP TABLE cont_tri');
        $this->addSql('DROP TABLE mini_jeu');
        $this->addSql('DROP TABLE suivi_prog');
    }
}
