<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260226234420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE joueur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pseudo VARCHAR(100) NOT NULL, score INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE session_jeu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_pin VARCHAR(10) NOT NULL, est_active BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE admin_jeu');
        $this->addSql('DROP TABLE joueur');
        $this->addSql('DROP TABLE session_jeu');
    }
}
