<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429120435 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE session_joueur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, tentatives_code_final INT NOT NULL, est_game_over BOOLEAN NOT NULL, a_gagne BOOLEAN NOT NULL, date_connexion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id INT NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_921AA39C613FECDF ON session_joueur (session_id)');
        $this->addSql('CREATE INDEX IDX_921AA39CA9E2D76C ON session_joueur (joueur_id)');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39C613FECDF FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_joueur ADD CONSTRAINT FK_921AA39CA9E2D76C FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT fk_b8596d5d613fecdf');
        $this->addSql('DROP INDEX idx_b8596d5d613fecdf');
        $this->addSql('ALTER TABLE inventaire_code RENAME COLUMN session_id TO session_joueur_id');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT FK_B8596D5DEA009266 FOREIGN KEY (session_joueur_id) REFERENCES session_joueur (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B8596D5DEA009266 ON inventaire_code (session_joueur_id)');
        $this->addSql('ALTER TABLE session_jeu DROP CONSTRAINT fk_ff3d158fa9e2d76c');
        $this->addSql('DROP INDEX idx_ff3d158fa9e2d76c');
        $this->addSql('ALTER TABLE session_jeu DROP score');
        $this->addSql('ALTER TABLE session_jeu DROP joueur_id');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT fk_9c9d174f613fecdf');
        $this->addSql('DROP INDEX idx_9c9d174f613fecdf');
        $this->addSql('DROP INDEX uniq_session_minijeu');
        $this->addSql('ALTER TABLE suivi_prog RENAME COLUMN session_id TO session_joueur_id');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT FK_9C9D174FEA009266 FOREIGN KEY (session_joueur_id) REFERENCES session_joueur (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_9C9D174FEA009266 ON suivi_prog (session_joueur_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_joueur_minijeu ON suivi_prog (session_joueur_id, mini_jeu_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE session_joueur DROP CONSTRAINT FK_921AA39C613FECDF');
        $this->addSql('ALTER TABLE session_joueur DROP CONSTRAINT FK_921AA39CA9E2D76C');
        $this->addSql('DROP TABLE session_joueur');
        $this->addSql('ALTER TABLE inventaire_code DROP CONSTRAINT FK_B8596D5DEA009266');
        $this->addSql('DROP INDEX IDX_B8596D5DEA009266');
        $this->addSql('ALTER TABLE inventaire_code RENAME COLUMN session_joueur_id TO session_id');
        $this->addSql('ALTER TABLE inventaire_code ADD CONSTRAINT fk_b8596d5d613fecdf FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_b8596d5d613fecdf ON inventaire_code (session_id)');
        $this->addSql('ALTER TABLE session_jeu ADD score INT NOT NULL');
        $this->addSql('ALTER TABLE session_jeu ADD joueur_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE session_jeu ADD CONSTRAINT fk_ff3d158fa9e2d76c FOREIGN KEY (joueur_id) REFERENCES joueur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_ff3d158fa9e2d76c ON session_jeu (joueur_id)');
        $this->addSql('ALTER TABLE suivi_prog DROP CONSTRAINT FK_9C9D174FEA009266');
        $this->addSql('DROP INDEX IDX_9C9D174FEA009266');
        $this->addSql('DROP INDEX uniq_session_joueur_minijeu');
        $this->addSql('ALTER TABLE suivi_prog RENAME COLUMN session_joueur_id TO session_id');
        $this->addSql('ALTER TABLE suivi_prog ADD CONSTRAINT fk_9c9d174f613fecdf FOREIGN KEY (session_id) REFERENCES session_jeu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_9c9d174f613fecdf ON suivi_prog (session_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_minijeu ON suivi_prog (session_id, mini_jeu_id)');
    }
}
